---
- name: Install Apache and Upload the page
  hosts: staging_servers
  become: yes

  vars:
    source_file: ./MyWebSite/index.html
    destin_file: /var/www/html

  tasks:
  - name: Install Apache Web Server
    apt: name=apache2 state=latest

  - name: Copy homepage
    copy: src={{ source_file }} dest={{ destin_file }} mode=0555
    notify: Restart Apache2

  - name: start Apache2 and enable
    service: name=apache2 state=started enabled=yes

  

  handlers:
  - name: Restart Apache2
    service: name=apache2 state=restarted
