---
- name: install and start apache2
  hosts: centos
  remote_user: ice
  become: yes

  tasks:
  - name: install epel repo
    yum: name=epel-release state=present

  - name: install apache2
    yum: name=httpd state=present
    
  - name: start apache2
    service: name=httpd state=started enabled=yes
